-- [Feature] User Blocking System (Corrected)
-- Aligning with existing 'blocks' table usage in App Code

-- 0. Cleanup wrong table if created
DROP TABLE IF EXISTS public.user_blocks;

-- 1. Create blocks table (if not exists)
CREATE TABLE IF NOT EXISTS public.blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    blocked_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(blocker_id, blocked_id)
);

-- 2. RLS Policies for blocks
ALTER TABLE public.blocks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own blocks" ON public.blocks;
DROP POLICY IF EXISTS "Users can add blocks" ON public.blocks;
DROP POLICY IF EXISTS "Users can remove blocks" ON public.blocks;

CREATE POLICY "Users can view their own blocks"
ON public.blocks FOR SELECT
USING (auth.uid() = blocker_id);

CREATE POLICY "Users can add blocks"
ON public.blocks FOR INSERT
WITH CHECK (auth.uid() = blocker_id);

CREATE POLICY "Users can remove blocks"
ON public.blocks FOR DELETE
USING (auth.uid() = blocker_id);

-- 3. Helpers (Optional, strictly speaking the app code does insert/delete directly)
