-- ==========================================
-- [fix_feed_features.sql]
-- Fix Feed View Count, Likes, and Implement Save (Bookmark)
-- ==========================================

-- 1. Create post_saves table (if not exists)
CREATE TABLE IF NOT EXISTS public.post_saves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    post_id BIGINT REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, post_id)
);

-- 2. RLS Policies for post_reviews (Feed) & Interaction Tables

-- Enable RLS
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_saves ENABLE ROW LEVEL SECURITY;

-- 2.1 Posts (Feeds)
-- Everyone can view posts
DROP POLICY IF EXISTS "Public posts are viewable by everyone" ON public.posts;
CREATE POLICY "Public posts are viewable by everyone"
ON public.posts FOR SELECT
USING (true);

-- Authenticated users can insert posts
DROP POLICY IF EXISTS "Users can insert their own posts" ON public.posts;
CREATE POLICY "Users can insert their own posts"
ON public.posts FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Users can update/delete their own posts
DROP POLICY IF EXISTS "Users can update their own posts" ON public.posts;
CREATE POLICY "Users can update their own posts"
ON public.posts FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own posts" ON public.posts;
CREATE POLICY "Users can delete their own posts"
ON public.posts FOR DELETE
TO authenticated
USING (auth.uid() = user_id);


-- 2.2 Post Likes
-- Everyone can view likes (to see counts)
DROP POLICY IF EXISTS "Likes are viewable by everyone" ON public.post_likes;
CREATE POLICY "Likes are viewable by everyone" 
ON public.post_likes FOR SELECT USING (true);

-- Authenticated users can insert (like)
DROP POLICY IF EXISTS "Users can insert likes" ON public.post_likes;
CREATE POLICY "Users can insert likes"
ON public.post_likes FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Authenticated users can delete (unlike)
DROP POLICY IF EXISTS "Users can delete their own likes" ON public.post_likes;
CREATE POLICY "Users can delete their own likes"
ON public.post_likes FOR DELETE
TO authenticated
USING (auth.uid() = user_id);


-- 2.3 Post Saves (Bookmarks) - NEW
-- Users can view their own saves (privacy)
DROP POLICY IF EXISTS "Users can view their own saves" ON public.post_saves;
CREATE POLICY "Users can view their own saves" 
ON public.post_saves FOR SELECT 
TO authenticated
USING (auth.uid() = user_id);

-- Authenticated users can insert (save)
DROP POLICY IF EXISTS "Users can insert saves" ON public.post_saves;
CREATE POLICY "Users can insert saves"
ON public.post_saves FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Authenticated users can delete (unsave)
DROP POLICY IF EXISTS "Users can delete their own saves" ON public.post_saves;
CREATE POLICY "Users can delete their own saves"
ON public.post_saves FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- 2.4 Helper Function for View Counts (Redundant safety if user missed previous file)
CREATE OR REPLACE FUNCTION public.increment_counter_int(table_name text, column_name text, row_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    EXECUTE format('UPDATE public.%I SET %I = COALESCE(%I, 0) + 1 WHERE id = $1', table_name, column_name, column_name)
    USING row_id;
END;
$$;

GRANT EXECUTE ON FUNCTION public.increment_counter_int(text, text, bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.increment_counter_int(text, text, bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.increment_counter_int(text, text, bigint) TO anon;

do $$
begin
    raise notice '✅ Feed features (Save, Like RLS, View Count) fixed successfully.';
end $$;
