-- [Fix] Final Comprehensive RLS & Permission Fixes
-- Addresses:
-- 1. review_votes RLS policy violation (Fix for 'Like' error)
-- 2. user_lists visibility for other users (Public lists)
-- 3. feed interactions (post_likes, post_saves) persistence

-- ==========================================
-- 1. REVIEW INTERACTIONS (Likes / Votes)
-- ==========================================

-- Check if review_votes exists, if not create or assume it handles likes/helpfuls
-- Note: User code uses 'review_votes' likely for 'Helpful' feature based on error log.

CREATE TABLE IF NOT EXISTS public.review_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT REFERENCES public.reviews(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    vote_type TEXT CHECK (vote_type IN ('helpful', 'like')) DEFAULT 'helpful', -- flexible
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(review_id, user_id)
);

ALTER TABLE public.review_votes ENABLE ROW LEVEL SECURITY;

-- Drop existing bad policies
DROP POLICY IF EXISTS "Enable read access for all users" ON public.review_votes;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.review_votes;
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON public.review_votes;
DROP POLICY IF EXISTS "Public can view votes" ON public.review_votes;
DROP POLICY IF EXISTS "Users can vote" ON public.review_votes;
DROP POLICY IF EXISTS "Users can remove vote" ON public.review_votes;

-- Re-create Policies
CREATE POLICY "Public can view votes"
ON public.review_votes FOR SELECT
USING (true);

CREATE POLICY "Users can vote"
ON public.review_votes FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can remove vote"
ON public.review_votes FOR DELETE
USING (auth.uid() = user_id);

-- [REMOVED] review_likes table policies as table does not exist and is successfully replaced by review_votes


-- ==========================================
-- 2. USER LISTS (Visibility)
-- ==========================================

ALTER TABLE public.user_lists ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can view public lists" ON public.user_lists;
DROP POLICY IF EXISTS "Users can view their own lists" ON public.user_lists;
DROP POLICY IF EXISTS "Users can manage their own lists" ON public.user_lists;
DROP POLICY IF EXISTS "Users can select their own lists" ON public.user_lists;
DROP POLICY IF EXISTS "Users can insert their own lists" ON public.user_lists;
DROP POLICY IF EXISTS "Users can update their own lists" ON public.user_lists;
DROP POLICY IF EXISTS "Users can delete their own lists" ON public.user_lists;
DROP POLICY IF EXISTS "Users can view own lists or public lists" ON public.user_lists;

-- New Combined Policies

-- SELECT: Owner sees all, Others see only is_public = true
CREATE POLICY "Users can view own lists or public lists"
ON public.user_lists FOR SELECT
USING (
    auth.uid() = user_id -- Owner
    OR 
    is_public = true -- Public
);

-- INSERT: Authenticated users can create
CREATE POLICY "Users can create lists"
ON public.user_lists FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- UPDATE: Owner only
CREATE POLICY "Users can update own lists"
ON public.user_lists FOR UPDATE
USING (auth.uid() = user_id);

-- DELETE: Owner only
CREATE POLICY "Users can delete own lists"
ON public.user_lists FOR DELETE
USING (auth.uid() = user_id);


-- ==========================================
-- 3. FEED INTERACTIONS (Double Check)
-- ==========================================

-- Post Saves
ALTER TABLE public.post_saves ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their own saves" ON public.post_saves;
DROP POLICY IF EXISTS "Users can insert their own saves" ON public.post_saves;
DROP POLICY IF EXISTS "Users can delete their own saves" ON public.post_saves;

CREATE POLICY "Users can view their own saves" 
ON public.post_saves FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own saves" 
ON public.post_saves FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own saves" 
ON public.post_saves FOR DELETE 
USING (auth.uid() = user_id);

-- Post Likes
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Likes are viewable by everyone" ON public.post_likes;
DROP POLICY IF EXISTS "Users can insert their own likes" ON public.post_likes;
DROP POLICY IF EXISTS "Users can delete their own likes" ON public.post_likes;

CREATE POLICY "Likes are viewable by everyone" 
ON public.post_likes FOR SELECT 
USING (true);

CREATE POLICY "Users can insert their own likes" 
ON public.post_likes FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own likes" 
ON public.post_likes FOR DELETE 
USING (auth.uid() = user_id);

-- ==========================================
-- 4. HELPER FUNCTION
-- ==========================================
-- Ensure increment function is accessible
GRANT EXECUTE ON FUNCTION public.increment_counter_int(text, text, bigint) TO authenticated, anon, service_role;

do $$
begin
    raise notice '✅ Fixed RLS for Reviews, User Lists, and Feed interactions.';
end $$;
