-- [Fix] Feed Features RLS & Schema (Final Robust Version)
-- This script fixes RLS policies and ensures columns exist.
-- Run this script in Supabase SQL Editor.

-- 0. Ensure 'view_count' column exists in posts
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS view_count INT DEFAULT 0;

-- 1. Ensure post_saves table exists
CREATE TABLE IF NOT EXISTS public.post_saves (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    post_id bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    UNIQUE(user_id, post_id)
);

-- 2. Enable RLS on all related tables
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_saves ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_comments ENABLE ROW LEVEL SECURITY;

-- 3. Drop existing policies to avoid conflicts (Clean Slate)

-- POSTS
DROP POLICY IF EXISTS "Enable read access for all users" ON public.posts;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.posts;
DROP POLICY IF EXISTS "Enable update for users based on user_id" ON public.posts;
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON public.posts;
DROP POLICY IF EXISTS "Public posts are viewable by everyone" ON public.posts;
DROP POLICY IF EXISTS "Users can insert their own posts" ON public.posts;
DROP POLICY IF EXISTS "Users can update their own posts" ON public.posts;
DROP POLICY IF EXISTS "Users can delete their own posts" ON public.posts;

-- POST_LIKES
DROP POLICY IF EXISTS "Enable read access for all users" ON public.post_likes;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.post_likes;
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON public.post_likes;
DROP POLICY IF EXISTS "Likes are viewable by everyone" ON public.post_likes;
DROP POLICY IF EXISTS "Users can insert their own likes" ON public.post_likes;
DROP POLICY IF EXISTS "Users can delete their own likes" ON public.post_likes;
DROP POLICY IF EXISTS "Users can insert likes" ON public.post_likes;

-- POST_SAVES
DROP POLICY IF EXISTS "Enable read access for all users" ON public.post_saves;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.post_saves;
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON public.post_saves;
DROP POLICY IF EXISTS "Saves are viewable by everyone" ON public.post_saves;
DROP POLICY IF EXISTS "Users can insert their own saves" ON public.post_saves;
DROP POLICY IF EXISTS "Users can delete their own saves" ON public.post_saves;
DROP POLICY IF EXISTS "Users can view their own saves" ON public.post_saves;
DROP POLICY IF EXISTS "Users can insert saves" ON public.post_saves;

-- POST_COMMENTS
DROP POLICY IF EXISTS "Comments are viewable by everyone" ON public.post_comments;
DROP POLICY IF EXISTS "Users can insert their own comments" ON public.post_comments;
DROP POLICY IF EXISTS "Users can delete their own comments" ON public.post_comments;


-- 4. Re-create Policies (Robust)

-- POSTS
CREATE POLICY "Public posts are viewable by everyone" 
ON public.posts FOR SELECT 
USING (true);

CREATE POLICY "Users can insert their own posts" 
ON public.posts FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own posts" 
ON public.posts FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own posts" 
ON public.posts FOR DELETE 
USING (auth.uid() = user_id);

-- POST_LIKES (Everyone can see likes to count them)
CREATE POLICY "Likes are viewable by everyone" 
ON public.post_likes FOR SELECT 
USING (true);

CREATE POLICY "Users can insert their own likes" 
ON public.post_likes FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own likes" 
ON public.post_likes FOR DELETE 
USING (auth.uid() = user_id);

-- POST_SAVES (Only I can see my saves)
CREATE POLICY "Users can view their own saves" 
ON public.post_saves FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own saves" 
ON public.post_saves FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own saves" 
ON public.post_saves FOR DELETE 
USING (auth.uid() = user_id);

-- POST_COMMENTS
CREATE POLICY "Comments are viewable by everyone" 
ON public.post_comments FOR SELECT 
USING (true);

CREATE POLICY "Users can insert their own comments" 
ON public.post_comments FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own comments" 
ON public.post_comments FOR DELETE 
USING (auth.uid() = user_id);


-- 5. Helper Functions (View Count)
CREATE OR REPLACE FUNCTION increment_counter_int(table_name TEXT, column_name TEXT, row_id INT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    EXECUTE format('UPDATE public.%I SET %I = COALESCE(%I, 0) + 1 WHERE id = $1', table_name, column_name, column_name)
    USING row_id;
END;
$$;
