
-- Reports Schema

create type report_reason as enum ('spam', 'abuse', 'explicit', 'flood', 'irrelevant', 'other');
create type report_status as enum ('pending', 'reviewed', 'resolved', 'dismissed');

create table public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references auth.users not null,
  target_type text not null check (target_type in ('post', 'comment', 'review', 'user')),
  target_id bigint not null, -- ID of the post, comment, etc.
  reason report_reason not null,
  description text null,
  status report_status default 'pending' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.reports enable row level security;

-- Reporters can view their own reports
create policy "Users can view own reports"
  on public.reports for select
  using (auth.uid() = reporter_id);

-- Reporters can create reports
create policy "Users can create reports"
  on public.reports for insert
  with check (auth.uid() = reporter_id);

-- Admins can view/update all reports (Assuming admin check function or role exists)
-- create policy "Admins can view all reports" on public.reports ... 
