
-- User Tastes Schema

-- Table for storing available taste tags
create table public.taste_tags (
  id bigint generated by default as identity primary key,
  tag_text text not null,
  category text null, -- e.g., 'food_type', 'mood', 'price_range'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table for storing user's selected tastes
create table public.user_tastes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  tag_id bigint references public.taste_tags(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, tag_id)
);

-- RLS Policies
alter table public.taste_tags enable row level security;
alter table public.user_tastes enable row level security;

-- Taste Tags: Everyone can read
create policy "Allow public read access for taste_tags"
  on public.taste_tags for select
  using (true);

-- User Tastes: Users can read/insert/delete their own data
create policy "Users can view their own tastes"
  on public.user_tastes for select
  using (auth.uid() = user_id);

create policy "Users can insert their own tastes"
  on public.user_tastes for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own tastes"
  on public.user_tastes for delete
  using (auth.uid() = user_id);

-- Initial Data Seeding (Korean)
insert into public.taste_tags (tag_text, category) values
('한식 파', 'food_type'),
('중식 러버', 'food_type'),
('일식 매니아', 'food_type'),
('양식 선호', 'food_type'),
('매운맛 고수', 'taste_preference'),
('맵찔이', 'taste_preference'),
('가성비 중시', 'value'),
('분위기 깡패', 'mood'),
('혼밥족', 'dining_style'),
('데이트 맛집', 'purpose'),
('디저트 필수', 'food_type'),
('노포 감성', 'mood');
